sudo: required
services:
  - docker

before_install:
  - docker build -t bankuyo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bankuyo/react-test npm test

after_success:
  - docker build -t bankuyo/multi-client ./client
  - docker build -t bankuyo/multi-nginx  ./nginx
  - docker build -t bankuyo/multi-worker ./worker
  - docker build -t bankuyo/multi-server ./server
  # Log in to the docker CLI 
    # => Create username and password environment variables
    # => Done at Travis CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push bankuyo/multi-client
  - docker push bankuyo/multi-nginx
  - docker push bankuyo/multi-worker
  - docker push bankuyo/multi-server